name: git Push

on:
  push:
    branches:
      - main

jobs:
  unzip-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install required packages
      run: |
        python -m pip install --upgrade pip
        pip install pyunpack

    - name: Find and unzip file
      run: |
        import os
        from pyunpack import Archive

        # Change directory to the main directory
        os.chdir('main')

        # Find all .zip files in the current directory
        zip_files = [f for f in os.listdir() if f.endswith('.zip')]

        if not zip_files:
          raise FileNotFoundError("No .zip files found in the main directory")

        # Assuming there is only one .zip file, extract it
        zip_file = zip_files[0]
        Archive(zip_file).extractall('.')

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Add changes to Git
      run: |
        git add .
        git commit -m "Unzipped files from $(basename $zip_file)"

    - name: Push changes to repository
      env:
        REPO_URL: https://github.com/wzsvip/git.git
      run: |
        git remote set-url origin $REPO_URL
        git push origin main
