name: Deploy Unzipped Files to Remote Repo

on:
  push:
    branches:
      - main

jobs:
  run-python-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyunpack

    - name: Run extract script
      run: python extract_files.py
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Run push script
      run: python push_to_remote.py
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}