name: git pull

on:
  workflow_dispatch:
    inputs:
      triggle:
        description: 'triggle'
  schedule:
     - cron:  '0 8,14,20,02 * * *' # 每6个小时触发一次
push:
    branches:
      - main

jobs:
  run-python-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies and patool
      run: |
        python -m pip install --upgrade pip
        pip install pyunpack patool
        pip install requests      
        
    - name: Run extract script
      run: python ${{ github.workspace }}/extract_files.py
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Run push script
      run: python ${{ github.workspace }}/push_to_remote.py
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        
    - name: 提交更改
      run: |
        git config --local user.email "wuzhij@mail.com"
        git config --local user.name "wzsvip"
        #git reset --hard origin/main
        git push -f 
